version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: atishayshukla/simple-app
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$SHORT_HASH
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$SHORT_HASH
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master